# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26ffa3f072153d217e6c16dcad8fe839ca50919426f220328db4ddfe05a59dcc50a88a6ac208672b3d6ba9b24eaa03f8b5995d1c547535724cdacf954f1efd65

test:
  secret_key_base: 26386f40645e52c13cfcd60822269e4a310403668396052854fd0768ecbbbee7e4bcea22c40ac5c0bff6bef656d3fdff3af77b52e77cb5339b9b7148c0089f1e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
